PageObject_Simple_Hw
nikitakunitsa/TAF pull request #4
Opened 2022-10-18 23:05 UTC by nikitakunitsa

Выполненное дз, за илсючением 4 тестов, на занятии в среду 19.10, кое что спрошу и доделаю

2022-10-26 14:26 UTC, wildpioneer commented
А что у тебя в репозитории папка target делает?

2022-10-26 14:29 UTC, wildpioneer commented
Общая проблема - форматирование

2022-10-26 14:34 UTC, wildpioneer requested changes

2022-10-26 14:34 UTC, wildpioneer commented on src/test/java/pages/CheckoutPage.java
> +    public CheckoutPage(WebDriver driver) {
Конструктор идет после описания переменных

2022-10-26 14:34 UTC, wildpioneer commented on src/test/java/pages/CheckoutPage.java
> +    public void gettext(){
Форматирование - где-то есть пустые строки после метода, где-то нет - надо единообразно делать

2022-10-26 14:34 UTC, wildpioneer commented on src/test/java/pages/CheckoutPage.java
> +    private final By errorButton=By.className("error-button");
Описание переменных в шапке должно быть

2022-10-26 14:34 UTC, wildpioneer commented on src/test/java/pages/CheckoutPage.java
> +    @Override
??? для чего этот метод?

2022-10-26 14:34 UTC, wildpioneer commented on src/test/java/pages/ManeMenuPage.java
> +    public void AddToShoppingCarsStep1Item() {
А если у тебя будет 30 steps - то для каждого будет отдельный метод?

2022-10-26 14:34 UTC, wildpioneer commented on src/test/java/steps/LoginStep.java
> +    public Boolean logOutTrue(){
Не понятный метод - а что он делает? Проверяет что кнопка есть?
И это является функциональным методом для системы?

2022-10-26 14:34 UTC, wildpioneer commented on src/test/java/steps/MainPageStep.java
> +        return null;
А почему везде null возвращается?

2022-10-26 14:34 UTC, wildpioneer commented on src/test/java/steps/MainPageStep.java
> +    public void someClickOnTwiter(){
Название метода - слово some тут несет какую-то смысловую нагрузку?

2022-10-27 12:21 UTC, nikitakunitsa commented on src/test/java/pages/CheckoutPage.java
> +    public CheckoutPage(WebDriver driver) {
исправил

2022-10-27 12:21 UTC, nikitakunitsa commented on src/test/java/pages/CheckoutPage.java
> +    public void gettext(){
исправил

2022-10-27 12:21 UTC, nikitakunitsa commented on src/test/java/pages/ManeMenuPage.java
> +    public void AddToShoppingCarsStep1Item() {
исправил, на добавление отдельно каждого товара

2022-10-27 12:22 UTC, nikitakunitsa commented on src/test/java/steps/MainPageStep.java
> +    public void someClickOnTwiter(){
исправил, когда писал, не обратил внимание

2022-10-27 12:22 UTC, nikitakunitsa commented on src/test/java/steps/MainPageStep.java
> +        return null;
тоже исправил

2022-10-27 12:23 UTC, nikitakunitsa commented on src/test/java/steps/LoginStep.java
> +    public Boolean logOutTrue(){
я хотел чтобы проверялось на успешность вылогинивания, но исправил на более просто механизм

2022-10-31 11:08 UTC, wildpioneer requested changes

2022-10-31 11:08 UTC, wildpioneer commented on src/test/java/steps/MainPageStep.java
> +    public void logout() {
Этот степ по логике должен относиться к LoginSteps

2022-10-31 11:08 UTC, wildpioneer commented on src/test/java/steps/MainPageStep.java
> +    public void clickButtonMenuPage() {
Это не функциональный степ - а просто нажатие на кнопку - т.е. атомарный метод

2022-10-31 11:08 UTC, wildpioneer commented on src/test/java/tests/MainMenuTest.java
> +    @Test
Пропустил пустые строки между методами - все в кучу - не читаемо

2022-10-31 11:08 UTC, wildpioneer commented on src/test/java/tests/MainMenuTest.java
> +    public void CliclButtonTwitterTest()throws InterruptedException{
Старайся перечитывать названия которые ты даешь методам - я понимаю, что английский хромает - но все же

2022-10-31 11:08 UTC, wildpioneer commented on src/test/java/pages/CheckoutPage.java
> +    public void setClickContinue() {
у метода Click не может быть сеттера - т.е.  set

2022-11-12 16:42 UTC, nikitakunitsa commented
Исправлено, можно проверить

2022-12-05 15:33 UTC, wildpioneer commented
Проверено

2022-12-05 15:33 UTC, closed without merging