Освноное дз выполнено, доп задание пока что не получается
nikitakunitsa/TAF pull request #5
Opened 2022-10-23 18:15 UTC by nikitakunitsa

2022-10-31 11:15 UTC, wildpioneer requested changes

2022-10-31 11:15 UTC, wildpioneer commented on src/test/java/tests/ActionsTest.java
> +        Assert.assertTrue(driver.findElement(By.xpath("//p[. ='Your content goes here.']")).getText()
Тут нужна небольшая пауза - потому что не всегда успевает переключиться перед началом проверки

2022-10-31 11:15 UTC, wildpioneer commented on src/test/java/tests/DomloadTest.java
> +        faildUpload.sendKeys("C:/Automation block/TAF/src/test/resources/test.jpg");
Путь должен быть построен программно - а не абсолютный

2022-10-31 11:15 UTC, wildpioneer commented on src/test/java/tests/DomloadTest.java
> +    }
После этого должна быть проверка - что файл загружен

2022-11-12 16:44 UTC, nikitakunitsa commented
Исправлены все ошибки, кроме пути нужно менять название папки, чтобы работало стабильно, можно закрыть пул реквест, на будущее буду знать что пробела не должно быть.

2022-12-05 15:33 UTC, wildpioneer commented
Проверено

2022-12-05 15:33 UTC, closed without merging